# Generated by Django 5.2.10 on 2026-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSupport', '0002_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent', max_length=20),
        ),
    ]
