# Generated by Django 5.2.10 on 2026-03-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSupport', '0005_report_approved_at_report_read_at_report_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
